### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by eturkel** [Boolean-Operator/EducationSherpa#1]
We're here to help you navigate the Delaware School Choice Process.(current)
Navigate the School Choice Program in Delaware. (new)
About
- https://www.doe.k12.de.us/domain/81 
- https://www.schoolchoicede.org/ChoiceApplications.aspx
- About
- the Choice Program
The Delaware School Choice Program began in the 1996-1997 School Year. The law addressing School Choice is found in 14 Del. C Chapter 4 (See Delaware Code online). There are no statewide regulations addressing the School Choice Program.
- Each receiving local education agency shall adopt and make available a policy regarding the order in which applications for enrollment shall be considered and the criteria by which such applications shall be evaluated for approval or disapproval pursuant to Title 14 § 405 . The receiving district’s policy shall seek to eliminate discrimination against choice students by: (1) allowing the receiving district to request supplemental application information from choice students only to the extent it requires the same information from attendance zone (resident school) students; (2) limiting the supplemental criteria a receiving district may use to evaluate choice applications—after that, receiving local education agencies must use a lottery system; and (3) removing the provision that allows a receiving local education agency to reject applications of students with special needs.
- All receiving local education agencies are required to use and accept the standard application form provided by the Delaware Department of Education (DDOE). The standard application form shall be made available on the DDOE’s website and all receiving local education agency websites.
- A parent residing within the State of Delaware may seek to enroll that parent's child in a Delaware public school in any school district, charter school, magnet school or vocational-technical school through the standard application form. Any student not currently registered in a public school in the State of Delaware must be registered in their School of Residence before submitting a standard application form.
- The standard application form may be accepted by the DOE and/or a receiving local education agency on or after the first Monday in November and on or before the second Wednesday in January. Charter schools, vocational-technical school districts, and magnet schools may continue to accept applications after the second Wednesday in January to fill remaining availability; however, those holding a lottery, will include applications received by the second Wednesday in January.
- A parent enrolling their child in kindergarten may submit the standard application form to the receiving local education agency up until the first day of the school year for enrollment in kindergarten during that school year. Pursuant to 14 Del.C. § 2702(b), a child shall be considered 5 years of age if that child celebrates the child's fifth birthday on or before August 31 of the respective year.
- Parents interested in applying to a district, charter school or career and technical education school should visit their website for information about the school and/or program and submission of a standard application form and any other supplemental application if required.
Navigate School Choice
- https://www.schoolchoicede.org/ 
- Timeline
1. Early Nov. - Window to submit school choice applications opens
2. Early Jan. - Window to submit school choice applications closes
3. Late submissions are allowed if "good cause" is provided
4. Late Feb. - Parents notified about invitation status
5. Mid March - Deadline to accept or deny school choice invitation
- Application
1. Applications to multiple schools can be submitted
2. Separate applications for each child must be sbi
- Invitation Status and Acceptance
IS THIS THE SAME ACROSS SCHOOL DISTRICTS? 
ACCEPTANCE CRITERIA (in order of priority):
Returning students who continue to meet the school requirements.
Siblings of students already enrolled in the school who will be returning to the school for the following academic year. Siblings of students living in the district will be given priority over siblings not living in the district.
Children of employees.
Students living within the Appoquinimink School District.
Students residing outside the district.

**Comment by Boolean-Operator** [comment]
I have tried to implement all of the changes you have outlined here, but I am not sure if this is exactly what you want.  Please feel free to email me directly or review the changes and let me know what you think

**Comment by eturkel** [comment]
Hi Mark,

I am still figuring out exactly what content I think should be displayed.
Betsey Suchanic is doing some resign work as well. We should have an update
in a couple of days. I'll make sure to keep you in the loop. Thanks for
keeping in touch.

Sincerely,

Eli

__

Eli Turkel*,* MPA
Research Assistant
Institute for Public Administration
University of Delaware
eturkel@udel.edu

On Sat, May 19, 2018 at 12:54 AM, Mark T. Graybill <notifications@github.com
